--Wood03_Expeditor

SELECT        
	SINGLEITEMORDERS.ORDNO
	, SINGLEITEMORDERS.ITEM
	, SINGLEITEMORDERS.MANUFORDER
	, SINGLEITEMORDERS.QTY
	, SINGLEITEMORDERS.MACDTE
	, SINGLEITEMORDERS.SHIPDT
	, SINGLEITEMORDERS.TRACKING
	, SINGLEITEMORDERS.JBCMPL
	, SINGLEITEMORDERS.PRMPLY
	, SINGLEITEMORDERS.SIDEFN
	, SINGLEITEMORDERS.DOORFN
	, SINGLEITEMORDERS.DOORWD
	, SINGLEITEMORDERS.SIDEWD
	, SINGLEITEMORDERS.STYLCD
	, SINGLEITEMORDERS.DSNGRP
	, SINGLEITEMORDERS.CABTYP
	, SINGLEITEMORDERS.CRDFLG
	, SINGLEITEMORDERS.WIDTH
	, SINGLEITEMORDERS.HEIGHT
	, SINGLEITEMORDERS.DEPTH
	, SINGLEITEMORDERS.LIGHT
	, SINGLEITEMORDERS.DARK
	, SINGLEITEMORDERS.OPAQUE
	, SINGLEITEMORDERS.[NATURAL]
	, SINGLEITEMORDERS.DESC1
	, SINGLEITEMORDERS.DESC2
	, SINGLEITEMORDERS.DESC3
	, SINGLEITEMORDERS.DESC4
	, SINGLEITEMORDERS.BLUECARD
	, SINGLEITEMORDERS.BLUECARDLABEL
	, SINGLEITEMORDERS.ALLINV
	, SINGLEITEMORDERS.PARTTYPE
	, CSSI_LOCATIONS_1.LOCATIONDESCRIPTION
	, SINGLEITEMORDERS.BCMOTRACKING
	, vLineupsCombined.TRUCK
	, SINGLEITEMORDERS.BCDELVRTODEPT
	, SINGLEITEMORDERS.BCDELVRTONAME
	, vExpeditorOrdersAll.TRACKING_MOD
	, vExpeditorOrdersAll.OP_WCKEY
	, vExpeditorOrdersAll.OP_WC_DESCR
	, vExpeditorOrdersAll.DLVRTOLOC
	, vExpeditorOrdersAll.DELVRNAME
	, vExpeditorOrdersAll.TRACKING_MOD_OP
	, vExpeditorOrdersAll.TRACKING_MOD_OP_DESCRIPTION
	, LOCATIONDURATION.DURATION
	, vExpeditorOrdersAll.MOS_DATE_REL
	, vExpeditorOrdersAll.TRACKING_DESCRIPTION
	, vExpeditorOrdersAll.BCREWORKDESC
	
FROM SINGLEITEMORDERS 
	LEFT OUTER JOIN LOCATIONDURATION ON SINGLEITEMORDERS.ITEM = LOCATIONDURATION.ITEM 
		AND SINGLEITEMORDERS.ORDNO = LOCATIONDURATION.ORDRNO 
    LEFT OUTER JOIN vExpeditorOrdersAll ON SINGLEITEMORDERS.MANUFORDER = vExpeditorOrdersAll.MONUMBER 
		AND SINGLEITEMORDERS.ORDNO = vExpeditorOrdersAll.ORDRNO 
		AND SINGLEITEMORDERS.ITEM = vExpeditorOrdersAll.ITEM 
    LEFT OUTER JOIN vLineupsCombined ON SINGLEITEMORDERS.ORDNO = vLineupsCombined.[ORDER] 
    LEFT OUTER JOIN PROFITKEYDB.pk1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_1 ON SINGLEITEMORDERS.TRACKING = CSSI_LOCATIONS_1.LOCATIONCODE
    
WHERE (SINGLEITEMORDERS.MACDTE <= @latestShipWeek) 
	AND (SINGLEITEMORDERS.PARTTYPE = @cabinetMisc) 
	AND (SINGLEITEMORDERS.PRMPLY <> 'X')