--WOOD03_Finishing
SELECT DISTINCT 'None' AS DEPARTMENT
FROM            PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_1
UNION ALL
SELECT DISTINCT DEPARTMENT
FROM            PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_2
WHERE        (DEPARTMENT IS NOT NULL)
UNION ALL
SELECT DISTINCT DEPARTMENT
FROM            PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS_MULTIPLE AS CSSI_LOCATIONS_MULTIPLE
WHERE        (DEPARTMENT IS NOT NULL) AND (DEPARTMENT NOT IN
                             (SELECT DISTINCT DEPARTMENT
                               FROM            PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_3
                               WHERE        (DEPARTMENT IS NOT NULL)))