--Directed to WOOD03_Finishing
SELECT DISTINCT 'None' AS AREALEADER

FROM PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_1

UNION ALL

SELECT DISTINCT AREALEADER

FROM PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_2

WHERE        (AREALEADER IS NOT NULL)

UNION ALL

SELECT DISTINCT AREALEADER

FROM            PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS_MULTIPLE AS CSSI_LOCATIONS_MULTIPLE

WHERE        (AREALEADER IS NOT NULL) AND (AREALEADER NOT IN

(SELECT DISTINCT AREALEADER
FROM PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_2
WHERE        (AREALEADER IS NOT NULL)))