--WOOD03_Expeditor
SELECT DISTINCT 'None' AS PLANTMANAGER
FROM         PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_1
UNION ALL
SELECT DISTINCT PLANTMANAGER
FROM         PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_2
WHERE     (PLANTMANAGER IS NOT NULL)