--Data Source=PROFITKEYDB;Initial Catalog=PK1

SELECT 'None' AS AREALEADER

FROM CSSI_LOCATIONS AS loc

UNION ALL

SELECT DISTINCT
	ISNULL(loc.AREALEADER, mult.AREALEADER) AS AREALEADER
	
FROM CSSI_LOCATIONS AS loc
FULL JOIN CSSI_LOCATIONS_MULTIPLE AS mult
	ON loc.AREALEADER = mult.AREALEADER

WHERE
	ISNULL(loc.AREALEADER, mult.AREALEADER) IS NOT NULL

ORDER BY
	AREALEADER