SELECT 'None' AS DEPARTMENT

UNION ALL

SELECT DISTINCT
	ISNULL(loc.DEPARTMENT, mult.DEPARTMENT)
	
FROM CSSI_LOCATIONS AS loc
FULL JOIN CSSI_LOCATIONS_MULTIPLE AS mult
	ON loc.DEPARTMENT = mult.DEPARTMENT

WHERE
	ISNULL(loc.DEPARTMENT, mult.DEPARTMENT) IS NOT NULL
	
ORDER BY
	DEPARTMENT