SELECT 'None' AS GROUPLEADER

UNION ALL

SELECT DISTINCT
	ISNULL(loc.GROUPLEADER, locbuild.GROUPLEADER) AS GROUPLEADER
	
FROM CSSI_LOCATIONS AS loc
FULL JOIN CSSI_LOCATIONSBUILDING as locbuild
	ON loc.GROUPLEADER = locbuild.GROUPLEADER
	
WHERE
	ISNULL(loc.GROUPLEADER, locbuild.GROUPLEADER) IS NOT NULL
	
ORDER BY
	GROUPLEADER