--WOOD03_Finishing
SELECT DISTINCT 'None' AS GROUPLEADER
FROM         PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_1
UNION ALL
SELECT DISTINCT 'All Locations' AS Expr1
FROM         PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_2
UNION ALL
SELECT DISTINCT GROUPLEADER
FROM         PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_3
WHERE     (GROUPLEADER IS NOT NULL)
UNION ALL
SELECT DISTINCT GROUPLEADER
FROM         PROFITKEYDB.PK1.dbo.CSSI_LOCATIONSBUILDING AS CSSI_LOCATIONSBUILDING
WHERE     (GROUPLEADER IS NOT NULL) AND (GROUPLEADER NOT IN
                          (SELECT DISTINCT GROUPLEADER
                            FROM          PROFITKEYDB.PK1.dbo.CSSI_LOCATIONS AS CSSI_LOCATIONS_3
                            WHERE      (GROUPLEADER IS NOT NULL)))